id: P008050
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ45267
  title: ལེའུ་བདུན་མ།
  author: ''
  volumes:
    7440bfa9345c4ad38ec9363e17918673:
      image_group_id: I4CZ45278
      title: ''
      volume_number: 1
      total_pages: 218
ebook_metadata:
  title: ལེའུ་བདུན་མ།
  author: ''
  sku: P008050
  cover: cover.jpg
  layers:
  - pagination
