id: P008050
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W4CZ45267
  title: ལེའུ་བདུན་མ།
  author: ''
  volumes:
    fdc803bfe85a47209724623442404cd7:
      image_group_id: I4CZ45278
      title: Volume 1 of le'u bdun ma/
      volume_number: 1
      total_pages: 218
      base_file: v001.txt
