id: opecha:P008050
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ45267
  title: ལེའུ་བདུན་མ།
  volume:
    fdc803bfe85a47209724623442404cd7:
      image_group_id: I4CZ45278
      title: Volume 1 of le'u bdun ma/
      volume_number: 1
      total_pages: 218
  author: ''
ebook_metadata:
  title: ལེའུ་བདུན་མ།
  author: ''
  sku: P008050
  cover: cover.jpg
  layers:
  - pagination
